name: moire-gen
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - dask
  - matplotlib
  - nodejs
  - distributed
  - jupyterlab
  - dask-labextension
  - ipywidgets
  - colorcet
  - scikit-image
  - scipy
