#!/bin/bash

# Install the JupyterLab dask-labextension
pip install dask-labextension

#jupyter labextension install --minimize=False --clean \
#    dask-labextension \
#    @jupyter-widgets/jupyterlab-manager
